#!/bin/sh

###########################################
## http://wiztools.org/project/WizCrypt/ ##
###########################################

## Version Information: To Be Changed During Release ##

VERSION=2.2

## Program logic starts, not to modify! ##

if which java > /dev/null 2>&1
then
	java -jar /usr/share/java/wizcrypt-${VERSION}-jar-with-dependencies.jar $*
else
	echo Java not in PATH
	exit 1
fi

