#!/bin/sh

###################################
## http://wizcrypt.wiztools.org/ ##
###################################

## Version Information: To Be Changed During Release ##

VERSION=2.2

## Program logic starts, not to modify! ##

if which java > /dev/null 2>&1
then
	java -client -jar /usr/share/java/wizcrypt-${VERSION}-jar-with-dependencies.jar $*
else
	echo Java not in PATH
	exit 1
fi

