#!/bin/sh

###########################################
## http://wiztools.org/project/WizCrypt/ ##
###########################################

if which java > /dev/null 2>&1
then
	java -jar /usr/share/java/WizCrypt-2.0-jar-with-dependencies.jar $*
else
	echo Java not in PATH
	exit 1
fi

